const SUBJECTS = window.QUIZ_DATA;
const QUESTIONS = window.QUESTIONS;
let subjectKey='all',unitKey='all',quiz=[],questionIndex=0,correct=0,mistakes=[];
const $=id=>document.getElementById(id);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function getUnitName(subject,unit){if(unit==='all')return'全単元';return SUBJECTS[subject]?.units.find(u=>u.id===unit)?.name||'単元';}
function getPool(subject,unit){return QUESTIONS.filter(q=>(subject==='all'||q.subject===subject)&&(unit==='all'||q.unit===unit));}
function renderHome(){const grid=$('subjectGrid');grid.innerHTML='';const all=document.createElement('button');all.className='subject-card overall';all.innerHTML=`<span class="subject-icon">🎯</span><div><b>五教科総合</b><small>国語・数学・理科・社会・英語</small><em>${QUESTIONS.length}問</em></div>`;all.onclick=()=>startQuiz('all','all');grid.appendChild(all);Object.entries(SUBJECTS).forEach(([key,s])=>{const b=document.createElement('button');b.className='subject-card';b.innerHTML=`<span class="subject-icon">${s.icon}</span><div><b>${s.name}</b><small>${s.description}</small><em>${s.units.length}単元 ・ ${QUESTIONS.filter(q=>q.subject===key).length}問</em></div>`;b.onclick=()=>openSubject(key);grid.appendChild(b);});}
function openSubject(key){subjectKey=key;unitKey='all';const s=SUBJECTS[key];$('subjectIcon').textContent=s.icon;$('subjectName').textContent=s.name;$('subjectDescription').textContent=s.description;const grid=$('unitGrid');grid.innerHTML='';const all=document.createElement('button');all.className='unit-card all-unit';all.innerHTML=`<span>📚</span><b>全単元</b><small>${getPool(key,'all').length}問から出題</small>`;all.onclick=()=>startQuiz(key,'all');grid.appendChild(all);s.units.forEach(u=>{const b=document.createElement('button');b.className='unit-card';b.innerHTML=`<span>${u.icon}</span><b>${u.name}</b><small>${getPool(key,u.id).length}問</small>`;b.onclick=()=>startQuiz(key,u.id);grid.appendChild(b);});showScreen('unitScreen');}
function startQuiz(subject,unit){const pool=getPool(subject,unit);if(!pool.length)return;subjectKey=subject;unitKey=unit;quiz=shuffle(pool).slice(0,Math.min(15,pool.length));questionIndex=0;correct=0;mistakes=[];showScreen('quizScreen');renderQuestion();}
function renderQuestion(){const q=quiz[questionIndex],name=subjectKey==='all'?'五教科総合':SUBJECTS[subjectKey].name;$('categoryLabel').textContent=name;$('questionNo').textContent=` ${questionIndex+1} / ${quiz.length}`;$('scoreLive').textContent=`${correct}問正解`;$('progressBar').style.width=`${questionIndex/quiz.length*100}%`;$('difficulty').textContent=q.difficulty;$('unitLabel').textContent=getUnitName(q.subject,q.unit);$('questionText').textContent=q.q;$('feedback').className='feedback hidden';$('nextButton').disabled=true;const answerText=q.a[q.answer],box=$('choices');box.innerHTML='';shuffle(q.a).forEach(choice=>{const b=document.createElement('button');b.className='choice';b.textContent=choice;b.onclick=()=>handleAnswer(choice,answerText,b,q);box.appendChild(b);});}
function handleAnswer(selected,answerText,selectedButton,q){const ok=selected===answerText;document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.textContent===answerText)b.classList.add('correct');if(!ok&&b===selectedButton)b.classList.add('wrong');});if(ok)correct++;else mistakes.push({...q,answerText});$('scoreLive').textContent=`${correct}問正解`;const f=$('feedback');f.className=`feedback ${ok?'good':'bad'}`;f.innerHTML=`<b>${ok?'正解！':'不正解。'}</b> ${q.e}`;$('nextButton').disabled=false;}
function finishQuiz(){showScreen('resultScreen');const score=Math.round(correct/quiz.length*100),name=subjectKey==='all'?'五教科総合':SUBJECTS[subjectKey].name,unitName=subjectKey==='all'?'':` / ${getUnitName(subjectKey,unitKey)}`;$('resultScore').textContent=score;$('scoreRing').style.setProperty('--score',score+'%');$('correctCount').textContent=correct;$('totalCount').textContent=quiz.length;$('accuracy').textContent=score+'%';$('resultSummary').textContent=`${name}${unitName}で${correct} / ${quiz.length}問正解。`;$('resultTitle').textContent=score===100?'全問正解！🎉':score>=90?'完璧に近い！🔥':score>=70?'いい調子！📚':'ここから伸ばそう！💪';const r=$('mistakeReview');r.innerHTML=mistakes.length?`<h3>間違えた問題 (${mistakes.length}問)</h3>`+mistakes.map(q=>`<div class="review-item"><div class="q">${q.q}</div><div class="a">正解：${q.answerText}<br>${q.e}</div></div>`).join(''):'<h3>すばらしい！</h3><p>間違えた問題はありません。</p>';const best=Math.max(Number(localStorage.getItem('fiveSubjectBest')||0),score);localStorage.setItem('fiveSubjectBest',best);renderBestScore();}
function renderBestScore(){const best=localStorage.getItem('fiveSubjectBest');$('bestScore').textContent=`最高得点：${best?best+'点':'—'}`;}
$('startAll').onclick=()=>startQuiz('all','all');$('backHome').onclick=()=>showScreen('homeScreen');$('nextButton').onclick=()=>{if(questionIndex+1<quiz.length){questionIndex++;renderQuestion();}else finishQuiz();};$('quitButton').onclick=()=>showScreen(subjectKey==='all'?'homeScreen':'unitScreen');$('retryButton').onclick=()=>startQuiz(subjectKey,unitKey);$('resultHomeButton').onclick=()=>showScreen('homeScreen');renderHome();renderBestScore();
